# Generated by Django 4.0.6 on 2022-07-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0002_repository_remove_mission_path_mission_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iac.repository'),
        ),
    ]
