# Generated by Django 4.0.6 on 2022-07-09 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0003_alter_mission_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='content',
        ),
        migrations.AddField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
