# Generated by Django 4.0.6 on 2022-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0004_remove_repository_content_repository_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='commit',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
