# Generated by Django 4.0.6 on 2022-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0007_mission_created_by_mission_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='inventories',
            field=models.TextField(null=True),
        ),
    ]
