# Generated by Django 4.0.6 on 2022-07-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0008_mission_inventories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('host', models.CharField(max_length=128)),
                ('play', models.CharField(max_length=128)),
                ('play_pattern', models.CharField(max_length=128)),
                ('task', models.CharField(max_length=128)),
                ('task_action', models.CharField(max_length=128)),
                ('task_args', models.TextField()),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('res', models.JSONField(null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iac.mission')),
            ],
        ),
    ]
