# Generated by Django 4.0.6 on 2022-07-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0010_missionevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionevent',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
