# Generated by Django 4.0.6 on 2022-07-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iac', '0014_mission_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playbook', models.CharField(max_length=64)),
                ('inventories', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iac.repository')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MissionTemplate',
        ),
    ]
