# Generated by Django 4.0.6 on 2022-07-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('iac', '0015_periodicmission_delete_missiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicmission',
            name='scheduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
        ),
    ]
